version: '3.5'

services:
  # --- ZABBIX SERVER & WEB ---
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix_root_pwd
    networks:
      - monitoring-net
    depends_on:
      - mysql-server

  zabbix-web-nginx:
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
      - "8080:8080"  # Acesso via http://localhost:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix_root_pwd
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=America/Sao_Paulo
    networks:
      - monitoring-net
    depends_on:
      - zabbix-server

  mysql-server:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./zbx_env/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=zabbix_root_pwd
    networks:
      - monitoring-net

  # --- OBJETOS GERENCIADOS (SIMULAÇÃO DAS VMs) ---
  
  vm1-rh:
    build: ./cliente-snmp  # Usa o Dockerfile que criamos
    hostname: vm1-rh
    deploy:
      resources:
        limits:
          memory: 128M     # Limitando RAM (Simulação de recurso escasso)
    networks:
      - monitoring-net

  vm2-financeiro:
    build: ./cliente-snmp
    hostname: vm2-financeiro
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - monitoring-net

  vm3-ti:
    build: ./cliente-snmp
    hostname: vm3-ti
    deploy:
      resources:
        limits:
          memory: 256M     # Um pouco mais de RAM para TI
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge